id: P264D4CA2
initial_creation_type: input
source_metadata:
  title: Khenchen Namdrol Tsering Series
  language: en
  description: 'A series of texts and teachings by the learned khenpo Namdrol Tsering
    (mkhan chen rnam grol tshe ring, b. 1953):'
  volume:
    8f0bb20ee4764b61bfb65dbe6fb1e040:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Oral Teachings
    2f9aa88ce9114cd3b7ee8b70e1d000cc:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Oral Teachings
created_at: '2022-03-01T00:20:48.877364'
last_modified_at: '2022-03-01T00:20:48.877370'
